#%RAML 1.0 Extension

extends: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.0.2/libraries/base-service.raml

title: EDA Workspace Subsetting Service API
version: v1.0.0
mediaType: application/json

uses:
  error: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.0.2/libraries/errors.raml
  lib: schema/library.raml

# TODO: THIS SHOULD BE HEADER
securitySchemes:
  header-auth:
    description: Authentication based on a WDK auth cookie.
    type:
      x-custom
    describedBy:
      headers:
        Auth_Key:
          description: Authorization header.
          type: string

#
# Endpoints
#

/studies:
  displayName: Available Studies
  get:
    responses:
      200:
        body:
          application/json:
            type: lib.StudiesGetResponse

  /clear-metadata-cache:
    displayName: Clears the metadata cache; useful if new data has been loaded into the database
    get:
      responses:
        202:

  /{study-id}:
    uriParameters:
      study-id:
        description: ID of the study of interest
        type: string
    get:
      responses:
        200:
          body:
            application/json:
              type: lib.StudyIdGetResponse

    /entities:

      /{entity-id}:
        uriParameters:
          entity-id:
            description: ID of the entity of interest
            type: string
        get:
          description: Returns entity details, not including its children (which it may or may not have; see study endpoint)
          responses:
            200:
              body:
                application/json:
                  type: lib.EntityIdGetResponse

        /count:
          post:
            securedBy: header-auth
            description: |
              Return a count of entities in this subset.  In the request, `filters` must be a subclass of [Filter](#type:lib.Filter)
            body:
              application/json:
                type: lib.EntityCountPostRequest
            responses:
              200:
                body:
                  application/json:
                    type: lib.EntityCountPostResponse
              401:
                body:
                  application/json:
                    type: error.UnauthorizedError
              500:
                body:
                  application/json:
                    type: error.ServerError

        /tabular:
          post:
            securedBy: header-auth
            description: |
             Return a tabular report of one or more variables belonging to this entity.  The output will also include all ancestor primary keys.  In the request, `filters` must be a subclass of [Filter](#type:lib.Filter)
            body:
              application/json:
                type: lib.EntityTabularPostRequest
            responses:
              200:
                body:
                  text/plain:
                    type: lib.EntityTabularPostResponse
              
              401:
                body:
                  application/json:
                    type: error.UnauthorizedError
              500:
                body:
                  application/json:
                    type: error.ServerError

        /variables:

          /{variable-id}:

            /distribution:
              post:
                securedBy: header-auth
                description: |
                  Return the count of entities in the subset that have a value for this variable, and |
                  a distribution for this variable, i.e., entity counts for each value of this |
                  variable.  In the request, `filters` must be a subclass of [Filter](#type:lib.Filter)
                body:
                  application/json:
                    type: lib.VariableDistributionPostRequest
                responses:
                  200:
                    body:
                      application/json:
                        type: lib.VariableDistributionPostResponse
                  401:
                    body:
                      application/json:
                        type: error.UnauthorizedError
                  500:
                    body:
                      application/json:
                        type: error.ServerError
