#%RAML 1.0 Extension

extends: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.0.1/libraries/base-service.raml

title: Example JaxRS Container Service
version: v1.0.0
mediaType: application/json

uses:
  error: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.0.1/libraries/errors.raml
  lib: schema/library.raml

# TODO: THIS SHOULD BE HEADER
securitySchemes:
  header-auth:
    description: Authentication based on a WDK auth cookie.
    type:
      x-custom
    describedBy:
      headers:
        Auth_Key:
          description: Authorization header.
          type: string


#
# Endpoints
#

/studies:
  displayName: Available Studies
  get:
    responses:
      200:
        body:
          application/json:
            type: lib.StudiesGetResponse

  /studies/{study-id}:
    uriParameters:
      study-id:
        description: ID of the study of interest
        type: string
    get:
      responses:
        200:
          body:
            application/json:
              type: lib.StudyIdGetResponse

    /studies/{study-id}/{entity-id}:
      uriParameters:
        study-id:
          description: ID of the study of interest
          type: string
        entity-id:
          description: ID of the entity of interest
          type: string
      get:
        responses:
          200:
            body:
              application/json:
                type: lib.EntityIdGetResponse

      post:
        securedBy: header-auth
        body:
          application/json:
            type: lib.EntityIdPostRequest
        responses:
          200:
            body:
              text/plain:
              
          401:
            body:
              application/json:
                type: error.UnauthorizedError
          500:
            body:
              application/json:
                type: error.ServerError

