#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.
  StudiesGetResponse:
    additionalProperties: false
    properties:
      studies:
        type: StudyOverview[]

  StudyIdGetResponse:
    additionalProperties: false
    properties:
      study:
        type: StudyDetail

  EntityIdGetResponse:
    additionalProperties: false
    properties:
      study:
        type: EntityVariable[]

  EntityIdPostRequest:
    additionalProperties: false
    properties:
      outputEntityId: string
      outputVariableIds?: string[]
      filters: Filter[]

  StudyOverview:
    type: object
    properties:
      id:
        required: true
        type: string
      name:
        required: true
        type: string

  StudyDetail:
    type: object
    properties:
      id: string
      name: string
      entityTree: Entity
      entityVariables:
        required: true
        type: EntityVariable[]

  Entity:
    type: object
    properties:
      id: string
      name: string
      description: string
      children?: Entity[]

  EntityVariable:
    type: object
    discriminator: type
    properties:
      id: string
      name: string
      description: string
      parentId?: string
      type: string # need to validate that this is string, number, date
          
  StringEntityVariable:
    type: EntityVariable
    discriminatorValue: string
    
  NumberEntityVariable:
    type: EntityVariable
    discriminatorValue: number
    properties:
      numberValueSpec:
        type: object
        properties:
          isContinuous: boolean
          precision: integer

  DateEntityVariable:
    type: EntityVariable
    discriminatorValue: date
    properties:
      dateValueSpec:
        type: object
        properties:
          isContinuous: boolean

  Filter:
    type: object
    discriminator: type
    properties:
      entityId: string
      variableId: string
      type: string # need to validate that this is stringSet, numberSet, dateSet, numberRange, dateRange
          
  StringSetFilter:
    type: Filter
    discriminatorValue: stringSet
    properties:
      stringSet: string[]

  NumberSetFilter:
    type: Filter
    discriminatorValue: numberSet
    properties:
      numberSet: number[]

  DateSetFilter:
    type: Filter
    discriminatorValue: dateSet
    properties:
      dateSet: string[]   # how to constrain this to a date?

  NumberRangeFilter:
    type: Filter
    discriminatorValue: numberRange
    properties:
      min: number
      max: number

  DateRangeFilter:
    type: Filter
    discriminatorValue: dateRange
    properties:
      min: string
      max: string




  

